version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:    
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: always
    depends_on:
      - db
    volumes:
      - ./prisma/db:/prisma/db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
